on:
  push:
    branches:
      - main
      - 'feat/*'
      - 'dev/*'
  pull_request:
    branches:
      - main
      - 'feat/*'
      - 'dev/*'

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 17 ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: gradle

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-jdk-${{ matrix.java-version }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-jdk-${{ matrix.java-version }}-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Verify Checksum
        run: |
          sha256sum app/build.gradle.kts > checksum.txt
          sha256sum app/src/main/java/com/pwhs/**/*.kt > checksum.txt
          
      - name: Upload checksum results
        uses: actions/upload-artifact@v4
        with:
          name: checksum-results
          path: checksum.txt

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app/build/outputs/**/*.apk
  test:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        java-version: [ 17 ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: gradle

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-jdk-${{ matrix.java-version }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-jdk-${{ matrix.java-version }}-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Unit Tests
        run: ./gradlew test

  notify:
    runs-on: ubuntu-latest
    needs: [ build, test ]
    if: always()

    steps:
      - uses: actions/checkout@v4

      - name: Send Telegram Notification on Success
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: html
          message: |
            ✅ <b>Build Succeeded</b>
            <b>Repository</b>: ${{ github.repository }}
            <b>Committer</b>: ${{ github.actor }}
            <b>Commit Message</b>: ${{ github.event.head_commit.message }}
            <b>Branch</b>: ${{ github.ref_name }}
            <b>Changes</b>: <a href="https://github.com/pass-with-high-score/quick_mem/commit/${{github.sha}}">View Changes</a>
            <b>Action</b>: <a href="https://github.com/pass-with-high-score/quick_mem/actions/runs/${{ github.run_id }}">View Action</a>

      - name: Send Telegram Notification on Failure
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: html
          message: |
            ❌ <b>Build Failed</b><br/>
            <b>Repository</b>: ${{ github.repository }}
            <b>Committer</b>: ${{ github.actor }}
            <b>Commit Message</b>: ${{ github.event.head_commit.message }}
            <b>Branch</b>: ${{ github.ref_name }}
            <b>Changes</b>: <a href="https://github.com/pass-with-high-score/quick_mem/commit/${{github.sha}}">View Changes</a>
            <b>Job Name</b>: ${{ github.job }}
            <b>Workflow Run</b>: <a href="https://github.com/pass-with-high-score/quick_mem/actions/runs/${{ github.run_id }}">View Details</a>
